name: project_sle
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  firebase_core: ^0.2.5+1
  cloud_firestore: ^0.8.0
  google_sign_in: ^3.2.2
  firebase_auth: ^0.6.2+1
  firebase_storage: ^1.0.4
  
  image_picker: ^0.4.10 
  device_info: ^0.2.1
  url_launcher: ^4.0.1
  charts_flutter: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/5.jpg
    - assets/images/6.jpg
    - assets/images/7.jpg
    - assets/images/8.jpg
    - assets/images/9.jpg
    - assets/images/10.jpg
    - assets/images/11.jpg
    - assets/images/12.jpg
    - assets/images/13.jpg
    - assets/images/14.jpg
    - assets/images/15.jpg
    - assets/images/16.jpg
    - assets/images/18.jpg
    - assets/images/19.jpg
    - assets/images/20.jpg
    - assets/images/21.jpg
    - assets/images/22.jpg
    - assets/images/23.jpg
    - assets/images/24.jpg
    - assets/images/25.jpg
    - assets/images/26.jpg
    - assets/images/28.jpg
    - assets/images/29.jpg
    - assets/images/30.jpg
    - assets/images/31.jpg
    - assets/images/32.jpg
    - assets/images/33.jpg
    - assets/images/34.jpg
    - assets/images/35.jpg
    - assets/images/36.jpg
    - assets/images/37.jpg
    - assets/images/38.jpg
    - assets/images/39.jpg
    - assets/images/40.jpg
    - assets/images/41.jpg
    - assets/images/43.jpg
